#' Create example data for testing and teaching purposes specifically for this package.
#'
#' @param what What do you want to create? Valid options are 'meta' (for a metadata table), 'asv' (for an ASV table), 'taxa' (for a taxonomy table) or 'all' or left blank to create a list of all three.
#'
#' @returns A metadata, ASV, or taxonomy table, or a list of all three.
#' @export
#' @import dplyr
#'
#' @examples
#' metadata <- makeExample("meta")
#' asvtable <- makeExample("asv")
#' taxa <- makeExample("taxa")
#' all <- makeExample() # OR:
#' all <- makeExample("all")
makeExample <- function(what = NULL) {
  if (is.null(what)) {
    return(list("metadata" = makeExampleMeta(), "asvtable" = makeExampleSeqtab(), "taxa" = makeExampleTaxa()))
  }
  if (what == "all") {
    return(list("metadata" = makeExampleMeta(), "asvtable" = makeExampleSeqtab(), "taxa" = makeExampleTaxa()))
  }
  if (what == "meta" | what == "metadata") {
    return(makeExampleMeta())
  }
  if (what == "asv" | what == "asvtable" | what == "seqtab") {
    return(makeExampleSeqtab())
  }
  if (what == "taxa" | what == "taxonomy") {
    return(makeExampleTaxa())
  }
  if (what != "meta" & what != "metadata" & what != "asv" & what != "asvtable" & what != "seqtab" & what != "taxa" & what != "taxonomy" & what != "all" & !is.null(what)) {
    stop("Valide options are 'all', 'meta' or 'metadata', 'asv' or 'asvtable' or 'seqtab', or 'taxa' or 'taxonomy'.")
  }
}

#' Create a simple metadata table
#'
#' @returns Simple metadata table for testing and demonstration.
#' @export
#'
#' @examples
#' metadata <- makeExampleMeta()
makeExampleMeta <- function() {
  tibble::tibble(
    SampleID = c("HC1", "HC2", "HC3", "Sick1", "Sick2", "Sick3", "Sick4", "ExtNegControl1", "ExtNegControl2", "PCRNegControl1", "PCRNegControl2", "PosControl1"),
    SampleType = c("nasal swab", "nasal swab", "nasal swab", "nasal swab", "nasal swab", "nasal swab", "nasal swab", "negative control", "negative control", "negative control", "negative control", "positive control"),
    HealthStatus = c("healthy", "healthy", "healthy", "sick", "sick", "sick", "sick", NA, NA, NA, NA, NA),
    Age = c(48, 32, 24, 42, 50, 45, 40, NA, NA, NA, NA, NA),
    Sex = c("female", "male", "female", "male", "male", "male", "female", NA, NA, NA, NA, NA),
    Location = c(NA, "urban", "urban", "rural", "urban", "rural", "urban", NA, NA, NA, NA, NA)
  )
}

#' Creates a simple example ASV table
#'
#' @returns A simple ASV table
#' @export
#'
#' @examples
#' makeExampleSeqtab()
makeExampleSeqtab <- function() {
  tibble::tibble(
    SampleID = c("HC1", "HC2", "HC3", "Sick1", "Sick2", "Sick3", "Sick4", "ExtNegControl1", "ExtNegControl2", "PCRNegControl1", "PCRNegControl2", "PosControl1"),
    TACGGAGGGTGCGAGCGTTAATCGGAATAACTGGGCGTAAAGGGCACGCAGGCGGTTATTTAAGTGAGGTGTGAAAGCCCTGGGCTTAACCTAGGAATTGCATTTCAGACTGGGTAACTAGAGTACTTTAGGGAGGGGTAGAATTCCACGTGTAGCGGTGAAATGCGTAGAGATGTGGAGGAATACCGAAGGCGAAGGCAGCCCCTTGGGAATGTACTGACGCTCATGTGCGAAAGCGTGGGGAGCAAACAGG = c(1856, 25732, 3385, 29939, 29954, 29724, 1, 12, 10, 0, 1, 10005),
    TACGGAAGGTCCAGGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGGCTGGAGATTAAGTGTGTTGTGAAATGTAGACGCTCAACGTCTGAATTGCAGCGCATACTGGTTTCCTTGAGTACGCACAACGTTGGCGGAATTCGTCGTGTAGCGGTGAAATGCTTAGATATGACGAAGAACTCCGATTGCGAAGGCAGCTGACGGGAGCGCAACTGACGCTTAAGCTCGAAGGTGCGGGTATCAAACAGG = c(11652, 4775, 6760, 26217, 16142, 2771, 2, 5, 3, 2, 1, 100024),
    TACGTAGGTGGCAAGCGTTATCCGGAATTATTGGGCGTAAAGCGCGCGTAGGCGGTTTTTTAAGTCTGATGTGAAAGCCCACGGCTCAACCGTGGAGGGTCATTGGAAACTGGAAAACTTGAGTGCAGAAGAGGAAAGTGGAATTCCATGTGTAGCGGTGAAATGCGCAGAGATATGGAGGAACACCAGTGGCGAAGGCGACTTTCTGGTCTGTAACTGACGCTGATGTGCGAAAGCGTGGGGATCAAACAGG = c(13681, 2902, 6184, 18965, 9656, 26380, 0, 10, 2, 0, 1, 10036),
    TACGGAGGGTGCGAGCGTTAATCGGAATAACTGGGCGTAAAGGGCACGCAGGCGGTTATTTAAGTGAGGTGTGAAAGCCCCGGGCTTAACCTGGGAATTGCATTTCAGACTGGGTAACTAGAGTACTTTAGGGAGGGGTAGAATTCCACGTGTAGCGGTGAAATGCGTAGAGATGTGGAGGAATACCGAAGGCGAAGGCAGCCCCTTGGGAATGTACTGACGCTCATGTGCGAAAGCGTGGGGAGCAAACAGG = c(2994, 1628, 569, 4483, 9373, 7803, 5, 21, 1, 0, 1, 0),
    TACGTAGGTCCCGAGCGTTGTCCGGATTTATTGGGCGTAAAGCGAGCGCAGGCGGTTAGATAAGTCTGAAGTTAAAGGCTGTGGCTTAACCATAGTAGGCTTTGGAAACTGTTTAACTTGAGTGCAAGAGGGGAGAGTGGAATTCCATGTGTAGCGGTGAAATGCGTAGATATATGGAGGAACACCGGTGGCGAAAGCGGCTCTCTGGCTTGTAACTGACGCTGAGGCTCGAAAGCGTGGGGAGCAAACAGG = c(9111, 1061, 7081, 3018, 3221, 8003, 1, 6, 0, 1, 1, 12040),
    TACGGAAGGTCCAGGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGGCGGACGATTAAGTCAGCTGTGAAAGTTTGCGGCTCAACCGTAAAATTGCAGTTGAAACTGGTTGTCTTGAGTGCACGCAGGGATGTTGGAATTCATGGTGTAGCGGTGAAATGCTTAGATATCATGAAGAACTCCGATCGCGAAGGCATATGTCTGGAGTGCAACTGACGCTGAGGCTCGAAAGTGCGGGTATCGAACAGG = c(3995, 13536, 8358, 217, 9506, 8157, 0, 0, 1, 1, 1, 0),
    TACGGAAGGTCCAGGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGGCGGATTGTTAAGTCAGCGGTTAAAGGGTGTGGCTCAACCATGCATTGCCGTTGAAACTGGCGATCTTGAGTGCAGACAGGGATGCCGGAATTCGTGGTGTAGCGGTGAAATGCTTAGATATCACGAAGAACTCCGATCGCGAAGGCAGGTGTCCGGGCTGCAACTGACGCTGAGGCTCGAAAGTGTGGGTATCAAACAGG = c(10821, 6216, 8780, 1599, 4237, 13010, 0, 0, 1, 1, 1, 0),
    TACGAAGGGTGCAAGCGTTACTCGGAATTACTGGGCGTAAAGCGTGCGTAGGTGGTCGTTTAAGTCCGTTGTGAAAGCCCTGGGCTCAACCTGGGAACTGCAGTGGATACTGGGCGACTAGAGTGTGGTAGAGGGTAGCGGAATTCCTGGTGTAGCAGTGAAATGCGTAGAGATCAGGAGGAACATCCATGGCGAAGGCAGCTACCTGGACCAACACTGACACTGAGGCACGAAAGCGTGGGGAGCAAACAGG = c(3937, 4089, 2907, 12441, 294, 8469, 0, 0, 1, 1, 1, 0),
    TACGGAAGGTCCAGGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGGCGGATTATTAAGTCAGTGGTGAAAGACGGTGGCTCAACCATCGTTAGCCATTGAAACTGGTAGTCTTGAGTGCAGACAGGGATGCTGGAACTCGTGGTGTAGCGGTGAAATGCTTAGATATCACGATGAACTCCAATCGCGAAGGCAGGTGTCCGGGCTGCAACTGACGCTGAGGCTCGAAAGTGTGGGTATCAAACAGG = c(4, 6, 8, 6, 6, 7, 1, 0, 1, 1, 1, 0)
  )
}

#' Create a simple taxonomy table
#'
#' @returns Simple taxonomy table for testing and demonstration purposes.
#' @export
#'
#' @examples
#' taxa <- makeExampleTaxa()
makeExampleTaxa <- function() {
  tibble::tibble(
    ASV = c("TACGGAGGGTGCGAGCGTTAATCGGAATAACTGGGCGTAAAGGGCACGCAGGCGGTTATTTAAGTGAGGTGTGAAAGCCCTGGGCTTAACCTAGGAATTGCATTTCAGACTGGGTAACTAGAGTACTTTAGGGAGGGGTAGAATTCCACGTGTAGCGGTGAAATGCGTAGAGATGTGGAGGAATACCGAAGGCGAAGGCAGCCCCTTGGGAATGTACTGACGCTCATGTGCGAAAGCGTGGGGAGCAAACAGG", "TACGGAAGGTCCAGGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGGCTGGAGATTAAGTGTGTTGTGAAATGTAGACGCTCAACGTCTGAATTGCAGCGCATACTGGTTTCCTTGAGTACGCACAACGTTGGCGGAATTCGTCGTGTAGCGGTGAAATGCTTAGATATGACGAAGAACTCCGATTGCGAAGGCAGCTGACGGGAGCGCAACTGACGCTTAAGCTCGAAGGTGCGGGTATCAAACAGG", "TACGTAGGTGGCAAGCGTTATCCGGAATTATTGGGCGTAAAGCGCGCGTAGGCGGTTTTTTAAGTCTGATGTGAAAGCCCACGGCTCAACCGTGGAGGGTCATTGGAAACTGGAAAACTTGAGTGCAGAAGAGGAAAGTGGAATTCCATGTGTAGCGGTGAAATGCGCAGAGATATGGAGGAACACCAGTGGCGAAGGCGACTTTCTGGTCTGTAACTGACGCTGATGTGCGAAAGCGTGGGGATCAAACAGG", "TACGGAGGGTGCGAGCGTTAATCGGAATAACTGGGCGTAAAGGGCACGCAGGCGGTTATTTAAGTGAGGTGTGAAAGCCCCGGGCTTAACCTGGGAATTGCATTTCAGACTGGGTAACTAGAGTACTTTAGGGAGGGGTAGAATTCCACGTGTAGCGGTGAAATGCGTAGAGATGTGGAGGAATACCGAAGGCGAAGGCAGCCCCTTGGGAATGTACTGACGCTCATGTGCGAAAGCGTGGGGAGCAAACAGG", "TACGTAGGTCCCGAGCGTTGTCCGGATTTATTGGGCGTAAAGCGAGCGCAGGCGGTTAGATAAGTCTGAAGTTAAAGGCTGTGGCTTAACCATAGTAGGCTTTGGAAACTGTTTAACTTGAGTGCAAGAGGGGAGAGTGGAATTCCATGTGTAGCGGTGAAATGCGTAGATATATGGAGGAACACCGGTGGCGAAAGCGGCTCTCTGGCTTGTAACTGACGCTGAGGCTCGAAAGCGTGGGGAGCAAACAGG", "TACGGAAGGTCCAGGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGGCGGACGATTAAGTCAGCTGTGAAAGTTTGCGGCTCAACCGTAAAATTGCAGTTGAAACTGGTTGTCTTGAGTGCACGCAGGGATGTTGGAATTCATGGTGTAGCGGTGAAATGCTTAGATATCATGAAGAACTCCGATCGCGAAGGCATATGTCTGGAGTGCAACTGACGCTGAGGCTCGAAAGTGCGGGTATCGAACAGG", "TACGGAAGGTCCAGGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGGCGGATTGTTAAGTCAGCGGTTAAAGGGTGTGGCTCAACCATGCATTGCCGTTGAAACTGGCGATCTTGAGTGCAGACAGGGATGCCGGAATTCGTGGTGTAGCGGTGAAATGCTTAGATATCACGAAGAACTCCGATCGCGAAGGCAGGTGTCCGGGCTGCAACTGACGCTGAGGCTCGAAAGTGTGGGTATCAAACAGG", "TACGAAGGGTGCAAGCGTTACTCGGAATTACTGGGCGTAAAGCGTGCGTAGGTGGTCGTTTAAGTCCGTTGTGAAAGCCCTGGGCTCAACCTGGGAACTGCAGTGGATACTGGGCGACTAGAGTGTGGTAGAGGGTAGCGGAATTCCTGGTGTAGCAGTGAAATGCGTAGAGATCAGGAGGAACATCCATGGCGAAGGCAGCTACCTGGACCAACACTGACACTGAGGCACGAAAGCGTGGGGAGCAAACAGG", "TACGGAAGGTCCAGGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGGCGGATTATTAAGTCAGTGGTGAAAGACGGTGGCTCAACCATCGTTAGCCATTGAAACTGGTAGTCTTGAGTGCAGACAGGGATGCTGGAACTCGTGGTGTAGCGGTGAAATGCTTAGATATCACGATGAACTCCAATCGCGAAGGCAGGTGTCCGGGCTGCAACTGACGCTGAGGCTCGAAAGTGTGGGTATCAAACAGG"),
    Kingdom = c(rep("Bacteria", 9)),
    Phylum = c("Proteobacteria", "Bacteroidota", "Firmicutes", "Proteobacteria", "Firmicutes", "Bacteroidota", "Bacteroidota", "Proteobacteria", "Bacteroidota"),
    Class = c("Gammaproteobacteria", "Bacteroidia", "Bacilli", "Gammaproteobacteria", "Bacilli", "Bacteroidia", "Bacteroidia", "Gammaproteobacteria", "Bacteroidia"),
    Order = c("Pasteurellales", "Bacteroidales", "Staphylococcales", "Pasteurellales", "Lactobacillales", "Bacteroidales", "Bacteroidales", "Xanthomonadales", "Bacteroidales"),
    Family = c("Pasteurellaceae", "Prevotellaceae", "Staphylococcaceae", "Pasteurellaceae", "Streptococcaceae", "Prevotellaceae", "Prevotellaceae", "Xanthomonadaceae", "Prevotellaceae"),
    Genus = c("Haemophilus", "Prevotella", "Staphylococcus", "Haemophilus", "Streptococcus", "Alloprevotella", "Alloprevotella", "Stenotrophomonas", "Alloprevotella"),
    Species = c(NA, "melaninogenica", NA, NA, NA, "rava", NA, NA, NA)
  )
}

